# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_body',
            field=models.TextField(null=True),
        ),
    ]
