# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_question_q_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_body',
            field=models.TextField(blank=True),
        ),
    ]
