# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20160322_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=userprofile.models.upload_location),
        ),
    ]
