# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160322_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
